Grebowicz wlodarczyk II
io2019/io2019 pull request #5
Opened 2020-01-10 16:05 UTC by Jakubgrebowicz

2020-01-10 16:05 UTC, Jakubgrebowicz commented
Czy ze strony kodu coś jeszcze oczekujecie?

2020-01-13 20:29 UTC, Adikso requested changes
Gdy w kliencie w JavaFX będziemy tworzyć np. nowy seans to będziemy potrzebowali wybrać sale i film z już istniejących.
Aby to było możliwe potrzebne jest zrobienie metod typu getShowrooms() getMovies() zwracających wszystkie sale i filmy jakie są dodane.

Potrzebne jest też zwracanie Showtime odbywających się w wybranym przedziale czasu, bo nie chcemy wysyłać wszystkich seansów jakie były w historii do klienta. Ale metodę zwracającą wszystko też dodajcie.

Przydałaby się też możliwość aktualizacji filmu, seansu, sali.

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +        for (Showtime existingShowtime: existingShowtimes) {
A jakby to wyszukiwanie przenieść do zapytania do bazy? W tych automatycznie generowanych zapytaniach jest Between. Bo jak sobie tak pomyślicie, że kino może latami działać to tak przeszukiwać w kodzie nie bardzo. Baza danych sprawniej sobie radzi z takim wyszukiwaniem.

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +    private boolean isShowtimeSameDayThatAnother(LocalDateTime date, Showtime existingShowtime){
Wtedy te wszystkie metody nie są potrzebne jeżeli przeniesiemy przeszukiwanie do bazy

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/MovieServiceImpl.java
> +        {
Raczej jak wszędzie robicie w tej samej lini klamrę to trzeba jednolicie wszędzie

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +        List < Showtime > existingShowtimes = showtimes.findShowtimesByShowroom(showtime.getShowroom());
Prosze włączyć autoformatowanie :(

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/MovieServiceImpl.java
> +        return (Movie) movies.findMovieById(id);
Kara chłosty za castowanie `List<Movie>` na Movie

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/MovieServiceImpl.java
> +        return (Movie) movies.findMovieByTitle(title);
100 batów za castowanie `List<Movie>` na Movie

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowroomServiceImpl.java
> +        return (Showroom) showrooms.findShowroomById(id);
Kamieniowanie za castowanie `List<Showroom>` na Showroom

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowroomServiceImpl.java
> +        return (Showroom) showrooms.findShowroomByName(name);
Nielegalne castowanie Listy na pojedynczy element
Proszę tak nie robić i najpierw wszystko przetestować czy to ma prawo działać

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +        return (Showtime) showtimes.findShowtimesByShowroom(showroom); }
Nielegalne castowanie Listy na pojedynczy element

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +    public Showtime getShowtimeByMovie(Movie movie) { return (Showtime) showtimes.findShowtimesByMovie(movie); }
Nielegalne castowanie Listy na pojedynczy element

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/MovieServiceImpl.java
> +        return (Movie) movies.findMovieById(id);
Tutaj też można użyć findById żeby zwrócić jeden film, bo id jest unikalne to zawsze zwróci jeden element

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowroomServiceImpl.java
> +        return (Showroom) showrooms.findShowroomById(id);
Tutaj też można użyć findById żeby zwrócić jeden showroom, bo id jest unikalne to zawsze zwróci jeden element

2020-01-13 20:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +    public Showtime getShowtimeById(long id) { return (Showtime) showtimes.findShowtimeById(id); }
Nielegalne castowanie Listy na pojedynczy element
Tutaj też można użyć findById żeby zwrócić jeden showtime, bo id jest unikalne to zawsze zwróci jeden element

2020-01-17 23:52 UTC, Jakubgrebowicz commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +        for (Showtime existingShowtime: existingShowtimes) {
Z drugiej strony po to ciągnę showtimes z danego showrooma (Co już mocno zawęża temat), a do tego sprawdzam czy zgadza się dzień, potem lecę z godzinami startu. 

Czy chodzi Ci o to, żeby z bazy wyciągnąć za pomocą between showtimesy z danego dnia, a potem "po staremu" obrobić w kodzie te godziny? Bo jak da się zauważyć z funkcji poniżej, jest kilka przypadków "nakładania się" dwóch seansów.

2020-01-17 23:52 UTC, Jakubgrebowicz commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +    private boolean isShowtimeSameDayThatAnother(LocalDateTime date, Showtime existingShowtime){
Odpowiedź wyżej

2020-01-18 07:20 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +        for (Showtime existingShowtime: existingShowtimes) {
Mi się wydaje, że coś w stylu:
```
select showtimes.*
from showtimes
         left join movies m on showtimes.movie_id = m.id
where date <= '2020-01-18 09:00:00'
  and DATEADD(MINUTE, duration, date) >= '2020-01-18 07:00:00'
  and showroom_id = 1
```
dałoby radę, bo zwraca ci nakładające się z danym przedziałem czasu seanse. Jeżeli cokolwiek ci zwróci to zapytanie to znaczy, że masz overlapa

2020-01-18 07:29 UTC, Adikso commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +        for (Showtime existingShowtime: existingShowtimes) {
Własne zapytania można robić typu:
```sql
@Query("SELECT u FROM User u WHERE u.status = :status and u.name = :name")
User findUserByStatusAndNameNamedParams(@Param("status") Integer status, @Param("name") String name);
```

2020-01-19 14:24 UTC, Adikso commented
Dodajcie jeszcze do Showroom, żeby był setter do noOfColumns i noOfRows

2020-01-19 17:49 UTC, LukaszWlodarczyk commented on src/main/java/net/io/kino/service/impl/ShowtimeServiceImpl.java
> +        for (Showtime existingShowtime: existingShowtimes) {
Poszło tylko u mnie kontroler nie działa i na każde zapytanie daje mi 400, więc ten select testowałem tylko na bazie danych a nie w apce, więc jak coś nie tak będzie to poprawię jeszcze.

2020-01-19 19:45 UTC, th7nder approved these changes

2020-01-19 19:45 UTC, merged